- name: base.yaml
  hosts: all
  tasks:
  - name: set timezone to Europe/Brussels
    timezone: name=Europe/Brussels

  - name: Install base packages
    yum: name={{ item }} state=latest
    with_items:
      - git
      - sudo
      - tcpdump
      - curl
      - wget
      - vim
      - ntp
      - lsof
      - info
      - logrotate
      - rsyslog
      - coreutils
      - findutils
      - gzip
      - hostname
      - iproute
      - sed
      - tar
      - bind-utils
    when:
      - ansible_distribution == "CentOS"

  - name: Copy /etc/ntp/ntp.conf
    template: src=templates/etc/ntp/ntp.conf dest=/etc/ntp/ntp.conf backup=yes
    when:
      - ansible_distribution == "CentOS"

  - name: Start and enable ntpd service
    systemd: name=ntpd state=restarted enabled=true
    when:
      - ansible_distribution == "CentOS"

  - name: Install base packages
    apt: name={{ item }} state=latest
    with_items:
      - git
      - sudo
      - tcpdump
      - curl
      - wget
      - vim
      - ntp
      - lsof
      - info
      - logrotate
      - rsyslog
      - coreutils
      - findutils
      - gzip
      - hostname
      - iproute
      - sed
      - tar
      - dnsutils
    when:
      - ansible_distribution == "Debian"
