- name: base.yaml
  hosts: all
  tasks:
  - name: set timezone to Europe/Brussels
    timezone: name=Europe/Brussels

  - name: Install base packages
    yum: name={{ item }} state=latest
    with_items:
      - git
      - tcpdump
      - curl
      - wget
      - vim
      - ntp
      - lsof
      - info
      - logrotate
      - rsyslog
      - coreutils
      - findutils
      - gzip
      - hostname
      - iproute
      - sed
      - tar
      - bind-utils

  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    become: true
    ignore_errors: true

  - name: waiting for server to come back
    local_action: wait_for port=22 host={{ inventory_hostname }} state=started delay=30 timeout=300
    become: false
