- name: galera.yaml
  hosts: all
  tasks:
  - name: Add galera repo
    yum_repository:
      name: MariaDB 10.1
      description: MariaDB 10.1 CentOS repository list
      baseurl: http://yum.mariadb.org/10.1/centos7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

  - name: Install MariaDB
    yum: name={{ item }}
    with_items:
      - mariadb-server
#      - mariadb-client

  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    become: true
    ignore_errors: true

  - name: waiting for server to come back
    local_action: wait_for port=22 host={{ inventory_hostname }} state=started delay=30 timeout=300
    become: false
