- name: update.yaml
  hosts: all
  tasks:
  - apt: upgrade=full update_cache=yes
    when:
      - ansible_distribution == "Debian"
  - yum: name=* state=latest update_cache=yes
    when:
      - ansible_distribution == "CentOS"
